routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('companies', 'CompanyController');
Route::resource('employees', 'EmployeeController');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'website', 'logo',
    ];

    public function employees()
    {
        return $this->hasMany('App\Employee');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Storage;

class CompanyController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::latest()->paginate(10);

        return view('companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'  => 'required',
            'email' => 'required|email',
        ]);

        $path = '';
        if($request->file('logo')) {
            $path = $request->file('logo')->store('companies', 'public');
        }

        $companyData = [
            'name'    => $request->name,
            'email'   => $request->email,
            'website' => $request->website,
            'logo'    => $path
        ];

        Company::create($companyData);

        return redirect()->route('companies.index')->with('success','Company created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        $request->validate([
            'name'  => 'required',
            'email' => 'required',
        ]);

        $companyData = [
            'name'    => $request->name,
            'email'   => $request->email,
            'website' => $request->website
        ];

        if($request->file('logo')) {
            $path = $request->file('logo')->store('companies', 'public');
            $companyData['logo'] = $path;
        }

        $company->update($companyData);
        
        return redirect()->route('companies.index')->with('success','Company updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();

        return redirect()->route('companies.index')->with('success','Company deleted successfully');
    }
}

resources/views/companies/create.blade.php
@extends('adminlte::page')

@section('title', 'Test App - Companies')

@section('content_header')
    <h1>Companies</h1>
@stop

@section('content')

    @if ($errors->any())

    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-warning"></i> There were some problems with your input.</h4>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
        
    @endif

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Add new company</h3>
        </div>
            <!-- /.box-header -->
            <!-- form start -->
        <form class="form-horizontal" action="{{ route('companies.store') }}" method="POST" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="box-body">
                <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" id="inputName" placeholder="Name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputWebsite" class="col-sm-2 control-label">Website</label>
                    <div class="col-sm-10">
                        <input type="text" name="website" class="form-control" id="inputWebsite" placeholder="Website">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputLogo" class="col-sm-2 control-label">Logo</label>
                    <div class="col-sm-10">
                        <input type="file" name="logo" class="form-control" id="inputLogo">
                        <!-- <input type="text" name="logo" class="form-control" id="inputLogo" placeholder="Logo"> -->
                    </div>
                </div>
            </div>
              <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-info pull-right">Save</button>
            </div>
              <!-- /.box-footer -->
        </form>
    </div>
@stop

resources/views/companies/edit.blade.php
@extends('adminlte::page')

@section('title', 'Test App - Companies')

@section('content_header')
    <h1>Companies</h1>
@stop

@section('content')

    @if ($errors->any())

    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-warning"></i> There were some problems with your input.</h4>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
        
    @endif

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Edit company</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" action="{{ route('companies.update', $company->id) }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="box-body">
                <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" value="{{ $company->name }}" class="form-control" id="inputName" placeholder="Name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" name="email" value="{{ $company->email }}" class="form-control" id="inputEmail" placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputWebsite" class="col-sm-2 control-label">Website</label>
                    <div class="col-sm-10">
                        <input type="text" name="website" value="{{ $company->website }}" class="form-control" id="inputWebsite" placeholder="Website">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputLogo" class="col-sm-2 control-label">Logo</label>
                    <div class="col-sm-10">
                        <input type="file" name="logo" class="form-control" id="inputLogo">
                        @if ($company->logo != "")
                        <img src="{{ URL::to('storage/'.$company->logo) }}" style="max-width: 600px; max-height: 500x;">
                        @endif  
                    </div>
                </div>
            </div>
              <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-info pull-right">Save</button>
            </div>
              <!-- /.box-footer -->
        </form>
    </div>
@stop

resources/views/companies/index.blade.php
@extends('adminlte::page')

@section('title', 'Test App - Companies')

@section('content_header')
    <h1>Companies</h1>
@stop

@section('content')

    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> Alert!</h4>
            {{ $message }}
        </div>
    @endif

    <div class="box">

        <div class="box-header with-border">
            <h3 class="box-title pull-left">List of Companies</h3>
            <div class="box-tools">
                <a href="{{ route('companies.create') }}" class="btn btn-block btn-default pull-right ">Add New</a>
            </div>
        </div>

        <div class="box-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Website</th>
                        <th>Action</th>
                    </tr>

                    @foreach ($companies as $company)
                    <tr>
                        <td>{{ $company->id }}</td>
                        <td>{{ $company->name }}</td>
                        <td>{{ $company->email }}</td>
                        <td>{{ $company->website }}</td>
                        <td>
                            <form action="{{ route('companies.destroy',$company->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{--@method('DELETE')--}}
                                {{ method_field('DELETE') }}
                                <a href="{{ route('companies.edit', $company->id) }}" class="btn btn-default btn-md">Edit</a>
                                <button type="submit" class="btn btn-default btn-md ">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
              </tbody>
            </table>
        </div>
    
        <div class="box-footer clearfix">
            <div class="pull-right">{!! $companies->links() !!}</div>
        </div>
        
    </div>

    
@stop