routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('companies', 'CompanyController');
Route::resource('employees', 'EmployeeController');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'company_id', 'email', 'phone'
    ];

    public function company()
    {
        return $this->belongsTo('App\Company', 'company_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\Company;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::latest()->with('Company')->paginate(10);

        return view('employees.index',compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();
        return view('employees.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name' => 'required',
            'last_name'  => 'required',
            'email'      => 'required|email'
        ]);

        Employee::create($request->all());

        return redirect()->route('employees.index')->with('success','Employee created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $companies = Company::all();
        return view('employees.edit', compact('employee', 'companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $request->validate([
            'first_name' => 'required',
            'last_name'  => 'required',
            'email'      => 'email'
        ]);

        $employee->update($request->all());

        return redirect()->route('employees.index')->with('success','Employee updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();

        return redirect()->route('employees.index')->with('success','Employee deleted successfully');
    }
}

resources/views/employees/create.blade.php
@extends('adminlte::page')

@section('title', 'Test App - Employees')

@section('content_header')
    <h1>Employees</h1>
@stop

@section('content')

    @if ($errors->any())

    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-warning"></i> There were some problems with your input.</h4>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
        
    @endif

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Add new employee</h3>
        </div>
        
        <form class="form-horizontal" action="{{ route('employees.store') }}" method="POST">
            {{csrf_field()}}
            <div class="box-body">
                <div class="form-group">
                    <label for="inputFName" class="col-sm-2 control-label">First Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="first_name" class="form-control" id="inputFName" placeholder="First Name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputLName" class="col-sm-2 control-label">Last Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="last_name" class="form-control" id="inputLName" placeholder="Last Name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputCompany" class="col-sm-2 control-label">Company</label>
                    <div class="col-sm-10">
                        <select name="company_id" class="form-control" id="inputCompany">
                        @foreach ($companies as $company)    
                            <option value="{{ $company->id }}">{{ $company->name }}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPhone" class="col-sm-2 control-label">Phone</label>
                    <div class="col-sm-10">
                        <input type="text" name="phone" class="form-control" id="inputPhone" placeholder="Phone">
                    </div>
                </div>
            </div>
              <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-info pull-right">Save</button>
            </div>
              <!-- /.box-footer -->
        </form>
    </div>
@stop

resources/views/employees/edit.blade.php
@extends('adminlte::page')

@section('title', 'Test App - Employees')

@section('content_header')
    <h1>Employees</h1>
@stop

@section('content')

    @if ($errors->any())

    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-warning"></i> There were some problems with your input.</h4>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
        
    @endif

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Edit employee</h3>
        </div>
        
        <form class="form-horizontal" action="{{ route('employees.update', $employee->id) }}" method="POST">
            {{csrf_field()}}
            {{ method_field('PUT') }}
            <div class="box-body">
                <div class="form-group">
                    <label for="inputFName" class="col-sm-2 control-label">First Name</label>
                    <div class="col-sm-10">
                        <input type="text" value="{{ $employee->first_name}}" name="first_name" class="form-control" id="inputFName" placeholder="First Name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputLName" class="col-sm-2 control-label">Last Name</label>
                    <div class="col-sm-10">
                        <input type="text" value="{{ $employee->last_name}}" name="last_name" class="form-control" id="inputLName" placeholder="Last Name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputCompany" class="col-sm-2 control-label">Company</label>
                    <div class="col-sm-10">
                        <select name="company_id" class="form-control" id="inputCompany">
                        @foreach ($companies as $company)    
                            <option value="{{ $company->id }}"
                            @if ($company->id == $employee->company_id)    
                                selected
                            @endif
                            >{{ $company->name }}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" value="{{ $employee->email }}" name="email" class="form-control" id="inputEmail" placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPhone" class="col-sm-2 control-label">Phone</label>
                    <div class="col-sm-10">
                        <input type="text" value="{{ $employee->phone }}" name="phone" class="form-control" id="inputPhone" placeholder="Phone">
                    </div>
                </div>
            </div>
              <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-info pull-right">Save</button>
            </div>
              <!-- /.box-footer -->
        </form>
    </div>
@stop

resources/views/employees/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Employees</h1>
@stop

@section('content')

    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> Alert!</h4>
            {{ $message }}
        </div>
    @endif

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title pull-left">List of Employees</h3>
            <div class="box-tools">
                <a href="{{ route('employees.create') }}" class="btn btn-block btn-default pull-right ">Add New</a>
            </div>
        </div>
        
        <div class="box-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Name</th>
                        <th>Company</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Action</th>
                    </tr>

                    @foreach ($employees as $employee)
                    <tr>
                        <td>{{ $employee->id  }}</td>
                        <td>{{ $employee->first_name }} {{ $employee->last_name }}</td>
                        <td>{{ $employee->company->name }}</td>
                        <td>{{ $employee->email }}</td>
                        <td>{{ $employee->phone }}</td>
                        <td>
                            <form action="{{ route('employees.destroy', $employee->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{--@method('DELETE')--}}
                                {{ method_field('DELETE') }}
                                <a href="{{ route('employees.edit', $employee->id) }}" class="btn btn-default btn-md">Edit</a>
                                <button type="submit" class="btn btn-default btn-md ">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
              </tbody>
            </table>
        </div>
    
        <div class="box-footer clearfix">
            <div class="pull-right">{!! $employees->links() !!}</div>
        </div>
    </div>
@stop